/**
 * Banes (Fraquezas) de cada clã de Vampiro: A Máscara V5
 * Mapeamento de clã para sua fraqueza específica
 */
export const clanBanes: Record<string, string> = {
  'Brujah': 'Os Brujah são passionais e estouram com extrema facilidade, sendo o clã mais suscetível a perder o controle para a Besta de Fúria. \nPenalidade: O personagem sofre uma subtração de dados igual à Gravidade da Perdição em qualquer teste feito para resistir a um Frenesi de Fúria.',
  'Gangrel': 'A Besta dos Gangrel é tão superficial que, quando eles perdem o controle, a sua própria carne assume traços e deformidades de animais selvagens. \nPenalidade: Sempre que o Gangrel entra em frenesi ou falha criticamente, ele ganha uma ou mais características animais físicas. Enquanto essas características durarem, o personagem sofre uma penalidade igual à Gravidade da Perdição em uma categoria de Atributos (geralmente Sociais ou Físicos, dependendo da mutação)',
  'Malkavian': 'O sangue dos Malkavianos é permanentemente fragmentado por uma loucura mística. Cada membro possui uma perturbação mental incurável. \nPenalidade: O personagem possui uma Perturbação permanente. Sempre que sua loucura se manifesta ativamente (em falhas ou compulsões), o Malkaviano sofre uma penalidade de dados igual à Gravidade da Perdição em todos os testes de uma categoria específica de Atributos (geralmente Mentais ou Sociais), devido à distração de suas neuroses.',
  'Nosferatu': 'Amaldiçoados por uma deformidade física absoluta, os Nosferatu são monstros hediondos cujo visual de pesadelo não pode ser mascarado por maquiagem ou meios mundanos. \nPenalidade: O personagem ganha automaticamente o defeito Repulsivo (••). Além disso, qualquer teste feito para disfarçar sua aparência ou agir furtivamente em situações onde sua deformidade possa ser notada sofre uma penalidade igual à Gravidade da Perdição.',
  'Toreador': 'Os Toreador são tão fissurados pelo belo que podem ficar completamente paralisados e hipnotizados ao presenciarem uma obra de arte, uma música perfeita ou um rosto bonito. \nPenalidade: Quando exposto a uma beleza avassaladora, o Toreador fica fascinado. Se ele tentar desviar o olhar, ignorar a beleza ou focar em qualquer outra ação física/mental, sofrerá uma penalidade igual à Gravidade da Perdição em todas as suas paradas de dados.',
  'Tremere': 'A feitiçaria que criou os Tremere corrompeu o poder de rebanho do seu sangue. A vitae deles perdeu a capacidade de escravizar emocionalmente outros membros da mesma espécie. \nPenalidade: O sangue Tremere nunca pode criar um Laço de Sangue com outros vampiros. Além disso, para conseguir criar um Laço de Sangue com um humano mortal, o Tremere precisa fazer o mortal beber de seu sangue um número de vezes/noites adicionais igual à Gravidade da Perdição.',
  'Ventrue': 'Os Ventrue possuem um paladar aristocrático e extremamente restrito. Eles são incapazes de digerir sangue comum que não pertença à sua linhagem de presas escolhida. \nPenalidade: O personagem só ganha sustento e reduz a Fome se beber de um tipo específico de mortal (ex: apenas mulheres ruivas, apenas criminosos, apenas aristocratas). Se tentar beber de qualquer outra fonte, o sangue parecerá cinza na boca e o Ventrue vomitará a vitae instantaneamente.',
  'Caitiff': 'Os Caitiff são párias sociais cujo sangue falhou em manifestar as características de uma linhagem específica. \nDesvantagem: Eles não têm uma perdição matemática escalável. A perdição deles é que eles não possuem Disciplinas de Clã. Para um Caitiff, comprar ou evoluir qualquer Disciplina na ficha custa sempre o valor mais caro de pontos de experiência (o preço de fora de clã). Socialmente, eles também ganham o defeito automático de serem vistos como "Suspeitos" pela sociedade.',
  'Lasombra': 'O vínculo dos Lasombra com o Abismo faz com que eles rejeitem a luz e o reflexo do mundo material, afetando diretamente a forma como interagem com tecnologias modernas. \nPenalidade: O reflexo do Lasombra aparece distorcido, trêmulo ou transparente em espelhos e câmeras. Qualquer teste feito para operar tecnologias modernas (computadores, celulares, sistemas de segurança) ou para evitar ser detectado por vigilância eletrônica sofre uma penalidade igual à Gravidade da Perdição.',
  'Tzimisce': 'Os Tzimisce são dragões ciumentos. Eles possuem uma necessidade obsessiva de fincar raízes e declarar posse sobre a terra onde descansam. \nPenalidade: O Tzimisce deve dormir cercado por pelo menos um punhado de terra de um local que tenha grande importância pessoal para ele (sua terra natal ou o local do seu Abraço). Se ele passar um dia descansando sem essa terra, ele sofre uma penalidade igual à Gravidade da Perdição em todas as suas paradas de dados de ação pelas próximas 24 horas.',
  'Ravnos': 'A destruição catastrófica de seu Antediluviano deixou uma marca de fogo e caos no sangue dos Ravnos. Eles estão condenados a nunca criar raízes, sob o risco de serem consumidos de dentro para fora. \nPenalidade: O Ravnos não pode dormir no mesmo lugar (ou num raio de 1,6 km dele) mais de uma vez a cada sete noites. Se ele quebrar essa regra e dormir no mesmo território, ele acorda sofrendo dano agravado na Vitalidade igual à Gravidade da Perdição devido ao sangue fervendo em suas veias.',
  'Banu Haqim': 'Os juízes da noite carregam uma maldição de sangue avassaladora: uma dependência e vício quase incontroláveis pela vitae de outros vampiros. \nPenalidade: Sempre que o Banu Haqim bebe ou saboreia a vitae de outro Membro (seja por heresia, punição ou acidente), ele deve fazer imediatamente um teste de Frenesi de Fome com uma penalidade igual à Gravidade da Perdição. Se falhar, ele entra em frenesi e tentará drenar o outro vampiro até a morte (cometendo Diablerie)',
  'Hecata': 'O Hecata (o clã unificado da morte) carrega a terrível maldição de que suas presas não transmitem o transe de prazer do êxtase vampírico. Sua mordida causa uma agonia horrível e gélida. \nPenalidade: Quando se alimentam de uma vítima viva, eles causam uma dor física excruciante. O Hecata sofre uma penalidade igual à Gravidade da Perdição em qualquer teste feito para manter a vítima calma, silenciosa ou cooperativa sem usar de violência física bruta. Mortais não controlados costumam gritar e lutar desesperadamente para fugir.',
  'Salubri': 'Os Salubri são caçados impiedosamente e carregam duas marcas terríveis em seu sangue: um estigma visual impossível de apagar e uma vitae incrivelmente desejável. \nPenalidade: O Salubri possui um terceiro olho físico no meio da testa. Sempre que ele usa qualquer poder de Disciplina de nível 2 ou maior, esse olho se abre e chora sangue. Tentar esconder o olho ou agir socialmente enquanto ele está aberto aplica uma penalidade igual à Gravidade da Perdição em testes sociais. Além disso, o sangue deles é tão doce que qualquer vampiro que o saboreie sente uma vontade incontrolável de cometer Diablerie no Salubri.',
  'O Ministério': 'Os herdeiros de Set carregam uma conexão tão profunda com as trevas espirituais que seus corpos reagem dolorosamente a qualquer tipo de iluminação intensa. \nPenalidade: Sempre que exposto a luzes muito fortes (holofotes, faróis altos de carros ou luzes de estúdio), o personagem sofre uma penalidade igual à Gravidade da Perdição em todas as suas paradas de dados de ação.',
  'Sangue Fraco': 'Membros de 15ª ou 16ª geração, cujo sangue está tão distante de Caim que eles flutuam entre o estado de vivos e mortos. Eles sempre possuem Potência do Sangue nível 0. \nDesvantagem: Eles não conseguem criar Laços de Sangue verdadeiros, têm chances quase nulas de abraçar novos vampiros com sucesso e não possuem Disciplinas naturais (usam a Alquimia de Sangue-Ralo). Na criação do personagem, o jogador é obrigado a escolher entre 1 e 3 Defeitos de Sangue-Ralo fixos da lista do livro (como Fragilidade Mortal, onde tomam dano de armas de fogo como humanos, ou Piscada de Bebê, onde continuam envelhecendo).',
}
